name: build-test-docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps 
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
          pip install flake8
          
      - name: Install project in editable mode
        run: pip install -e .
      
      - name: Lint
        run: |
          flake8 src || true

      - name: Test
        run: pytest tests/

      - name: Build Docker image
        run: docker build -t fashion-mnist .

      - name: Train in Docker (CPU)
        run: docker run --rm -e MODE=train fashion-mnist

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: src/fashion_mnist/model.pth
      - name: Build and install package
        run: pip install .
