name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install deps (host for lint/test)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint
      run: flake8 src

    - name: Test
      run: pytest -q

    - name: Build Docker image
      run: docker build -t fashion-mnist .

    - name: Train in Docker (CPU)
      run: docker run --rm -e MODE=train -v ${{ github.workspace }}/src:/app/src fashion-mnist

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: src/model.pth

    - name: Build and install package
      run: pip install .

